export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_DELETE_ITEM = 'TODO_DELETE_ITEM';
export const TODO_SELECT_ITEM = 'TODO_SELECT_ITEM';
export const TODO_GET_ALL_ITEMS = 'TODO_GET_ALL_ITEMS';